### ISSUE TITLE
Monolog Handler

### ISSUE THREAD

**Issue by soullivaneuh** [ManneW/HipChatBundle#10]
As GitLab notifications on HipChat, it would be great to have a Monolog Handler to push error on a specific room.

The configuration could be like this:

``` yaml
monolog:
    handlers:
        buffered:
            type:    buffer
            handler: hipchat
        hipchat:
            type:       hipchat
            room:     53145
            notify:     false
```

What do you think?
